blank_issues_enabled: true
contact_links:
  - name: General question / contact AICHIS
    url: https://github.com/AICHIS-org/AICHIS.org.github.io/discussions
    about: For general questions or conversations, please use Discussions.
